# Generated by Django 5.2.17 on 2026-10-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltag",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
