# Generated by Django 5.2.13 on 2026-05-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_text", models.TextField()),
                ("extracted_keywords", models.JSONField(blank=True, default=list)),
                ("suggested_skill_names", models.JSONField(blank=True, default=list)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="profiles.studentprofile",
                    ),
                ),
            ],
        ),
    ]
