# Generated by Django 5.2.17 on 2026-10-02 02:57

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_vector_extension"),
        ("discovery", "0002_full_text_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilesearchindex",
            name="embedding",
        ),
        migrations.AddField(
            model_name="profilesearchindex",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profilesearchindex",
            name="embedding_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profilesearchindex",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profilesearchindex",
            name="embedding_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profilesearchindex",
            name="vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.CreateModel(
            name="EmbeddingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("queued_until", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=80)),
                (
                    "index",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_job",
                        to="discovery.profilesearchindex",
                    ),
                ),
            ],
        ),
    ]
