# Generated by Django 5.2.17 on 2026-10-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_remove_profilesearchindex_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingjob",
            name="processing_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
