import {useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';
import {useQuery, useQueryClient} from '@tanstack/react-query';
import {useAuth} from '../hooks/useAuth';
import {useCurrentProfile, useProfileEditor} from '../hooks/useProfileEditor';
import {useToast} from '../components/ui/ToastProvider';
import {api} from '../lib/api';
import {getAllPages} from '../lib/pagination';
import {apiErrorMessage} from '../lib/errors';

export function SettingsPage() {
  const auth = useAuth(); const navigate = useNavigate(); const toast = useToast(); const client = useQueryClient();
  const profile = useCurrentProfile(); const editor = useProfileEditor();
  const blocks = useQuery({queryKey: ['blocked-users'], queryFn: () => getAllPages<{id: number; blocked_label: string}>('/blocked-users/')});
  const [confirmation, setConfirmation] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  const change = async (payload: Parameters<typeof editor.updateProfile.mutateAsync>[0]) => {try {await editor.updateProfile.mutateAsync(payload); toast.success('Preference saved.');} catch (e) {setError(apiErrorMessage(e));}};
  return <div className="mx-auto max-w-3xl space-y-6"><div><h1 className="text-3xl font-bold">Settings</h1><p className="text-[#475569]">Manage your account and privacy.</p></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
    <section className="space-y-3 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Account</h2><p>{auth.user?.email}</p><p className="text-sm text-[#475569]">Illinois email ownership was verified. This does not imply university approval or current enrollment.</p><Link className="underline" to="/profile/edit">Edit profile and avatar</Link></section>
    <section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Privacy and availability</h2>{profile.isLoading ? <p role="status">Loading preferences…</p> : profile.isError ? <p role="alert">Preferences could not be loaded.</p> : <>
      <label className="flex items-center gap-3"><input type="checkbox" disabled={editor.updateProfile.isPending} checked={profile.data?.visibility === 'public'} onChange={e => void change({visibility: e.target.checked ? 'public' : 'private'})}/>Published for eligible signed-in members</label>
      <label className="flex items-center gap-3"><input type="checkbox" disabled={editor.updateProfile.isPending} checked={profile.data?.open_to_connect || false} onChange={e => void change({open_to_connect: e.target.checked})}/>Willing to help</label>
      <label className="flex items-center gap-3"><input type="checkbox" disabled={editor.updateProfile.isPending} checked={profile.data?.share_contacts || false} onChange={e => void change({share_contacts: e.target.checked})}/>Share selected contacts after acceptance</label>
      <label className="flex items-center gap-3"><input type="checkbox" disabled={editor.updateProfile.isPending} checked={profile.data?.embedding_consent || false} onChange={e => void change({embedding_consent: e.target.checked})}/>Allow published skill text for semantic matching when enabled</label>
      <label className="flex items-center gap-3"><input type="checkbox" disabled={editor.updateProfile.isPending} checked={profile.data?.notification_email_enabled || false} onChange={e => void change({notification_email_enabled: e.target.checked})}/>Email me request and feedback updates</label>
      <p className="text-sm text-[#475569]">Paid calls are disabled. Withdrawing consent or blocking a peer revokes further sharing.</p>
    </>}<div className="flex flex-wrap gap-4"><Link className="underline" to="/profile/edit?tab=contact">Manage contact methods</Link><Link className="underline" to="/profile/edit?tab=credentials">Manage evidence links</Link><Link className="underline" to="/profile/edit?tab=basic">Manage learning goals</Link></div></section>
    <section className="space-y-3 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Blocked users</h2>{blocks.isLoading ? <p role="status">Loading blocks…</p> : blocks.isError ? <p role="alert">Could not load blocked users.</p> : blocks.data?.length ? blocks.data.map(block => <div key={block.id} className="flex justify-between gap-3"><span>{block.blocked_label}</span><button className="underline" onClick={async () => {try {await api.delete(`/blocked-users/${block.id}/`); await client.invalidateQueries(); toast.success('User unblocked. Cancelled requests remain cancelled.');} catch (e) {setError(apiErrorMessage(e));}}}>Unblock {block.blocked_label}</button></div>) : <p>No blocked users.</p>}</section>
    <section className="space-y-3 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Your data</h2><button disabled={pending} className="rounded-lg border px-4 py-2" onClick={async () => {setPending(true); try {const {data} = await api.get('/auth/export/', {responseType: 'blob'}); const url = URL.createObjectURL(data); const link = document.createElement('a'); link.href = url; link.download = 'skillshare-account.json'; link.click(); URL.revokeObjectURL(url);} catch (e) {setError(apiErrorMessage(e));} finally {setPending(false);}}}>Export my account data</button><p className="text-sm text-[#475569]">Deletion removes your profile, avatar, search data, contacts and interactions, and revokes every session. Minimal moderation audit records remain without your account identity.</p><label className="block text-sm">Type your email to confirm permanent deletion<input className="mt-2 w-full rounded-lg border p-3" value={confirmation} onChange={e => setConfirmation(e.target.value)}/></label><button disabled={pending || confirmation !== auth.user?.email} className="rounded-lg border border-red-700 px-4 py-2 text-red-700 disabled:opacity-40" onClick={async () => {setPending(true); try {await api.post('/auth/delete/', {confirmation}); await auth.refreshSession(); navigate('/login', {replace: true});} catch (e) {setError(apiErrorMessage(e));} finally {setPending(false);}}}>Delete my account permanently</button></section>
    <button className="w-full rounded-xl border p-3" onClick={async () => {try {await auth.logout(); navigate('/login', {replace: true});} catch (e) {setError(apiErrorMessage(e));}}}>Sign out</button>
  </div>;
}
