import type {ProfileFormState} from '../../lib/profilePersistence';
import type {SkillTag} from '../../types/api';

export function LearningGoals({form, skills, onChange}: {form: ProfileFormState; skills: SkillTag[]; onChange: (next: ProfileFormState) => void}) {
  return <fieldset className="space-y-3 rounded-xl border p-4"><legend className="font-semibold">What would you like to learn?</legend><p className="text-sm text-[#475569]">These goals personalize recommendations and stay private.</p><div className="flex flex-wrap gap-2">{skills.map(skill => <button type="button" key={skill.id} aria-pressed={form.learningGoalIds.includes(skill.id)} onClick={() => onChange({...form, learningGoalIds: form.learningGoalIds.includes(skill.id) ? form.learningGoalIds.filter(id => id !== skill.id) : [...form.learningGoalIds, skill.id]})} className={`rounded-full border px-3 py-2 text-sm ${form.learningGoalIds.includes(skill.id) ? 'bg-[#13294B] text-white' : 'bg-white'}`}>{skill.name}</button>)}</div><label className="block text-sm">Specific learning goal (optional)<textarea maxLength={500} className="mt-1 w-full rounded-lg border p-2" value={form.learningGoalNotes} onChange={event => onChange({...form, learningGoalNotes: event.target.value})}/></label></fieldset>;
}

export function SharingPreferences({form, onChange}: {form: ProfileFormState; onChange: (next: ProfileFormState) => void}) {
  return <fieldset className="space-y-3 rounded-xl border p-4"><legend className="font-semibold">Your sharing choices</legend><label className="flex items-start gap-2"><input type="checkbox" checked={form.visibility === 'public'} onChange={event => onChange({...form, visibility: event.target.checked ? 'public' : 'private'})}/>Publish my profile for eligible signed-in members</label><label className="flex items-start gap-2"><input type="checkbox" checked={form.shareContacts} onChange={event => onChange({...form, shareContacts: event.target.checked})}/>Share selected contact methods after a request is accepted</label><label className="flex items-start gap-2"><input type="checkbox" checked={form.embeddingConsent} onChange={event => onChange({...form, embeddingConsent: event.target.checked})}/>Allow published skill descriptions, headline and bio to be used for semantic matching when enabled</label><p className="text-xs text-[#475569]">Paid AI calls are currently disabled. Contact details and private learning goals are never embedded.</p></fieldset>;
}
