\set ON_ERROR_STOP on
SELECT format('CREATE ROLE skillshare_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD %L', :'runtime_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'skillshare_app') \gexec
SELECT format('ALTER ROLE skillshare_app PASSWORD %L', :'runtime_password') \gexec
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE skillshare TO skillshare_app;
GRANT USAGE ON SCHEMA public TO skillshare_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO skillshare_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO skillshare_app;
ALTER DEFAULT PRIVILEGES FOR ROLE skillshare IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO skillshare_app;
ALTER DEFAULT PRIVILEGES FOR ROLE skillshare IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO skillshare_app;
