# Generated by Django 5.2.17 on 2026-10-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="availability_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="embedding_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="learning_goal_notes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="learning_goals",
            field=models.ManyToManyField(
                blank=True, related_name="learners", to="taxonomy.skilltag"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="share_contacts",
            field=models.BooleanField(default=False),
        ),
    ]
