# Generated by Django 5.2.17 on 2026-10-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_studentprofile_availability_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="notification_email_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
