# Generated by Django 5.2.13 on 2026-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interactions",
            "0002_helprequest_accepted_at_helprequest_cancelled_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("portfolio", "Portfolio"),
                    ("website", "Website"),
                    ("other", "Other"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
