# Generated by Django 5.2.17 on 2026-10-02 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_blockeduser_blocked_label_moderationaudit"),
        ("profiles", "0002_studentprofile_availability_confirmed_at_and_more"),
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsement",
            name="help_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endorsements",
                to="interactions.helprequest",
            ),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="idempotency_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="topic_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="review",
            name="help_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="interactions.helprequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="helprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("seeker", "idempotency_key"),
                name="unique_request_submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="helprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "accepted"]),
                    models.Q(("topic_key", ""), _negated=True),
                ),
                fields=("seeker", "helper_profile", "topic_key"),
                name="unique_active_help_topic",
            ),
        ),
    ]
